### ISSUE TITLE
A few more bugs with Py3.2...

### ISSUE THREAD

**Issue by canardleteer** [ybrs/pydisque#13]
SUMMARY: Just a warning for other people who may be interested in using this library with Python 3.2!

I found a few more bugs in Python 3.2 execution while writing some new unit tests for new Disque commands. 

Mostly, I was brutally sloppy in implementing the 'six' library, but as learning some more complete Py2->Py3 transitional code is something of interest to me, I'm more then happy to take the task upon myself to fix it.

**Comment by ybrs** [comment]
I went through tests today - yes after a few years :) -, fixed a few bytes -> string issues. running the lib. against python 3.7.2 without issues now. 

So closing this issue.
