### ISSUE TITLE
What do you think of doing a 0.1.2 release?

### ISSUE THREAD

**Issue by canardleteer** [ybrs/pydisque#27]
Heya ybrs,

What do you think about incrementing the version number and doing a release to PyPI?

I started breaking out some milestones a few weeks ago (https://github.com/ybrs/pydisque/milestones) and I think we've hit what I originally put into 0.1.2. I'm always up for more + feedback.

**Comment by skyrocknroll** [comment]
seems like 0.1.1 is too outdated. lets release updated version in pip

**Comment by ybrs** [comment]
sorry for the late reply. updated & uploaded pypi 

https://pypi.python.org/pypi/pydisque/0.1.2

@canardleteer thanks for your work :)

**Comment by canardleteer** [comment]
Oooh, over 100 downloads right away on PyPI. 

Don't sweat late replies, I'm super busy these days as well. Thank you for all your work on this project. I'm excited to get a little time for a 0.2.0 release.
