### ISSUE TITLE
async is a reserved word in python 3.7

### ISSUE THREAD

**Issue by benbro** [ybrs/pydisque#38]
[async](https://docs.python.org/3/reference/compound_stmts.html#async) is a reserved word in python 3.7.

[This](https://github.com/ybrs/pydisque/blob/master/pydisque/client.py#L171) breaks:
``` python
def add_job(self, queue_name, job, timeout=200, replicate=None, delay=None,
retry=None, ttl=None, maxlen=None, async=None):
```

**Comment by abdul-khalid** [comment]
Yes, async is reserved keyword in python3.7
For temporary fix just rename this variable to something else in add_job function in pydisque/client.py

**Comment by benbro** [comment]
Fixed with:
https://github.com/ybrs/pydisque/pull/39
